/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsNumber,
} from "class-validator";
import { ImageCreateNestedManyWithoutToursInput, RatingCreateNestedManyWithoutToursInput } from "./ImageCreateNestedManyWithoutToursInput";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class TourCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ImageCreateNestedManyWithoutToursInput,
  })
  @ValidateNested()
  @Type(() => ImageCreateNestedManyWithoutToursInput)
  @IsOptional()
  @Field(() => ImageCreateNestedManyWithoutToursInput, {
    nullable: true,
  })
  images?: ImageCreateNestedManyWithoutToursInput;

  @ApiProperty({
    required: false,
    type: () => RatingCreateNestedManyWithoutToursInput,
  })
  @ValidateNested()
  @Type(() => RatingCreateNestedManyWithoutToursInput)
  @IsOptional()
  @Field(() => RatingCreateNestedManyWithoutToursInput, {
    nullable: true,
  })
  ratings?: RatingCreateNestedManyWithoutToursInput;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  latitude!: number;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  longitude!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { TourCreateInput as TourCreateInput };
